NCI-Agency/anet#2954: Make LikertScale onChange required when editable
This makes sure we no longer get the error "Uncaught TypeError:
onChange is not a function" when clicking on the LikertScale while
it is not editable (like on the task show page, or in the
ReportStatistics).